/**
 * Deck analysis over the baked Scryfall data.
 *
 * Pure — no DOM. The data is generated by scripts/fetch-cards.mjs and shipped
 * as JSON, so nothing here needs the network.
 */

import raw from "./mtg-data.json"

export interface Card {
  name: string
  cmc: number
  cost: string
  type: string
  fullType: string
  colors: string[]
  rarity: string
  set: string
  text: string
}

export interface DeckEntry {
  count: number
  name: string
}

export interface Deck {
  id: string
  commander: string
  entries: DeckEntry[]
}

const DATA = raw as unknown as {
  generated: string
  decks: Deck[]
  cards: Record<string, Card>
}

export const DECKS: Deck[] = DATA.decks
export const CARDS: Record<string, Card> = DATA.cards
export const GENERATED = DATA.generated

export const cardByName = (name: string): Card | undefined => CARDS[name]

/**
 * A deck's display name, taken from its commander.
 *
 * Derived rather than hardcoded: a hand-written map went stale immediately —
 * the bears list is commanded by Beorn the Fierce, not by Ayula, who is merely
 * in it. The part before the comma keeps tab labels short.
 */
export function deckTitle(d: Deck): string {
  const card = cardByName(d.commander)
  return (card?.name ?? d.commander).split(",")[0]
}

export const WUBRG = ["W", "U", "B", "R", "G"] as const
export type Colour = (typeof WUBRG)[number]

export const COLOUR_NAME: Record<Colour | "C", string> = {
  W: "white",
  U: "blue",
  B: "black",
  R: "red",
  G: "green",
  C: "colourless",
}

/** Total cards, counting duplicates. A legal Commander deck totals 100. */
export function deckSize(d: Deck): number {
  return 1 + d.entries.reduce((n, e) => n + e.count, 0)
}

/**
 * Mana curve, excluding lands.
 *
 * Lands are omitted because they have no mana value and would pile a
 * meaningless spike onto the zero column, drowning the shape of the curve.
 */
export function manaCurve(d: Deck): { cmc: number; count: number }[] {
  const buckets = new Map<number, number>()
  for (const e of d.entries) {
    const card = cardByName(e.name)
    if (!card || isLand(card)) continue
    const key = Math.min(7, Math.floor(card.cmc))
    buckets.set(key, (buckets.get(key) ?? 0) + e.count)
  }
  return Array.from({ length: 8 }, (_, cmc) => ({
    cmc,
    count: buckets.get(cmc) ?? 0,
  }))
}

export const isLand = (c: Card): boolean => c.type.includes("Land")

/** Colour pips across the deck's colour identity, counting duplicates. */
export function colourSpread(d: Deck): Record<Colour | "C", number> {
  const out: Record<Colour | "C", number> = { W: 0, U: 0, B: 0, R: 0, G: 0, C: 0 }
  for (const e of [{ count: 1, name: d.commander }, ...d.entries]) {
    const card = cardByName(e.name)
    if (!card) continue
    if (card.colors.length === 0) out.C += e.count
    else for (const c of card.colors) out[c as Colour] += e.count
  }
  return out
}

/** Card counts by primary type, most common first. */
export function typeSpread(d: Deck): { type: string; count: number }[] {
  const buckets = new Map<string, number>()
  for (const e of d.entries) {
    const card = cardByName(e.name)
    if (!card) continue
    // "Legendary Creature" and "Creature" are the same thing for a breakdown.
    const key =
      ["Creature", "Instant", "Sorcery", "Artifact", "Enchantment", "Land", "Planeswalker", "Battle"].find(
        (t) => card.type.includes(t)
      ) ?? "Other"
    buckets.set(key, (buckets.get(key) ?? 0) + e.count)
  }
  return [...buckets.entries()]
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count)
}

/** Average mana value of the non-land cards. */
export function averageCmc(d: Deck): number {
  let total = 0
  let n = 0
  for (const e of d.entries) {
    const card = cardByName(e.name)
    if (!card || isLand(card)) continue
    total += card.cmc * e.count
    n += e.count
  }
  return n === 0 ? 0 : total / n
}

/** The deck's cards in display order: commander, then by type then cost. */
export function sortedEntries(d: Deck): DeckEntry[] {
  const ORDER = [
    "Creature",
    "Planeswalker",
    "Instant",
    "Sorcery",
    "Artifact",
    "Enchantment",
    "Battle",
    "Land",
  ]
  const rank = (name: string) => {
    const c = cardByName(name)
    if (!c) return ORDER.length
    const i = ORDER.findIndex((t) => c.type.includes(t))
    return i === -1 ? ORDER.length : i
  }
  return [...d.entries].sort((a, b) => {
    const ra = rank(a.name)
    const rb = rank(b.name)
    if (ra !== rb) return ra - rb
    const ca = cardByName(a.name)?.cmc ?? 0
    const cb = cardByName(b.name)?.cmc ?? 0
    if (ca !== cb) return ca - cb
    return a.name.localeCompare(b.name)
  })
}

/**
 * Splits a mana cost string into its symbols: "{2}{W}{W}" -> ["2","W","W"].
 *
 * Returned bare so the renderer can draw each pip itself rather than trying to
 * style a single string.
 */
export function costSymbols(cost: string): string[] {
  return [...cost.matchAll(/\{([^}]+)\}/g)].map((m) => m[1])
}

/* ── Pack opening ─────────────────────────────────────────────────────── */

export interface Pack {
  cards: Card[]
}

const RARITY_ORDER = ["common", "uncommon", "rare", "mythic"] as const

export const PACK_SIZE = 14
/** Every pack has exactly one land, as a real booster does. */
export const LANDS_PER_PACK = 1
export const UNCOMMONS_PER_PACK = 3

/**
 * Opens a pack drawn from the cards across all three decks.
 *
 * This is a pack from *his collection*, not a real product: the pool is
 * whatever he actually plays. The slot structure follows a modern booster —
 * one land, one to three rares or mythics, three uncommons, commons for the
 * rest — because that shape is what makes opening one feel like opening one.
 *
 * The land is its own slot rather than something the other slots can roll,
 * which is what keeps a pack from coming out half basics.
 */
export function openPack(rng: () => number = Math.random): Pack {
  const pool = Object.values(CARDS)
  const lands = pool.filter(isLand)
  const spells = pool.filter((c) => !isLand(c))

  const byRarity = new Map<string, Card[]>()
  for (const c of spells) {
    const key = RARITY_ORDER.includes(c.rarity as never) ? c.rarity : "common"
    const list = byRarity.get(key) ?? []
    list.push(c)
    byRarity.set(key, list)
  }

  // Sampling without replacement, across the whole pack: no pack repeats a card.
  const taken = new Set<string>()
  const take = (from: Card[], n: number): Card[] => {
    const available = from.filter((c) => !taken.has(c.name))
    const picked: Card[] = []
    for (let i = 0; i < n && picked.length < available.length; i++) {
      let idx = Math.floor(rng() * available.length)
      let guard = 0
      while (taken.has(available[idx].name) && guard++ < available.length) {
        idx = (idx + 1) % available.length
      }
      const card = available[idx]
      if (taken.has(card.name)) break
      taken.add(card.name)
      picked.push(card)
    }
    return picked
  }

  // One rare, with a chance at a second and a slimmer one at a third.
  let rares = 1
  if (rng() < 0.26) rares++
  if (rares === 2 && rng() < 0.22) rares++

  const top: Card[] = []
  for (let i = 0; i < rares; i++) {
    // Roughly one rare slot in eight is a mythic, as in a real booster.
    const wantMythic = rng() < 0.125
    const drawn = wantMythic
      ? take(byRarity.get("mythic") ?? [], 1)
      : take(byRarity.get("rare") ?? [], 1)
    top.push(...(drawn.length ? drawn : take(byRarity.get("rare") ?? [], 1)))
  }

  const uncommons = take(byRarity.get("uncommon") ?? [], UNCOMMONS_PER_PACK)
  const land = take(lands, LANDS_PER_PACK)
  const commons = take(
    byRarity.get("common") ?? [],
    PACK_SIZE - top.length - uncommons.length - land.length
  )

  return { cards: [...top, ...uncommons, ...commons, ...land] }
}
